// A modest list of profanity blocked in DisKids.
// Replace or extend as needed. Matching is case-insensitive and
// attempts to ignore basic punctuation and repeated characters.
export const BAD_WORDS = [
  'damn',
  'crap',
  'hell',
  'shit',
  'piss',
  'bastard',
  'bitch',
  'asshole',
  'dick',
  'fuck',
  'fucker',
  'fucking',
  'ass',
  'jackass',
  'douche',
  'douchebag',
  'jerkwad',
  'slut',
  'whore',
  'bloody',
  'bollocks',
  'wanker',
  'prick',
  'twat',
  'arsehole',
  'arse',
  'bugger',
  'godod',
];